### ISSUE TITLE
Failed download, returning error: 404

### ISSUE THREAD

**Issue by Profility** [hare1039/iwara-dl#11]
When I try to download all videos from a user, I get this error **"curl: (22) The requested URL returned a error: 404"**

When I try to play the video in the Iwara website, I get an error saying **"The media could not be loaded, either because the server or network failed or because the format is not supported."**

I am running the script in Windows using WSL2 Ubuntu

Is this the website's fault?

**Comment by hare1039** [comment]
Yes, if the website does not provide the download links, which may be still being processing, `iwara-dl` cannot download it. 
You can try to download the video later.

**Comment by hare1039** [comment]
Close due to no updates
