### ISSUE TITLE
Error when running iwara-dl

### ISSUE THREAD

**Issue by Lighting-Angel** [hare1039/iwara-dl#14]
Firstly, Is it fine to run this using Git Bash for Windows? I tried executing the command as follows:
sh iwara-dl.sh [Playlist URL]

to download a playlist but it returns with an error 
./iwaralib.sh: line 11: `calc-argc': not a valid identifier

So I checked the file using notepad and changed - to _ for all the functions until it stopped throwing that error

Then when I try running it, I get the following error
iwara_dl.sh: line 142: calc-argc: command not found
Missing [urls/ids]

I tried sh iwara-dl.sh url [Playlist URL] & sh iwara-dl.sh -url [Playlist URL] but the issue still persists...

I'm new to coding so apologies if this problem sounds very basic :)

PS/Edit: Unrelated to this, but do u have any solution for videos in playlists just randomly disappearing? I had around 140 but now it only shows 30 :(

**Comment by hare1039** [comment]
@Lighting-Angel I tried to run `iwara-dl` on fresh git-bash windows, and it should work =>
![image](https://user-images.githubusercontent.com/17266862/204120313-9be2df28-489f-42f8-a321-8d21ddda2e07.png)

So in the installing step, I only need to install `jq` (by this command `curl -L -o /usr/bin/jq.exe https://github.com/stedolan/jq/releases/latest/download/jq-win64.exe` in the administrator mode)  and python3 
![image](https://user-images.githubusercontent.com/17266862/204120368-a30133a2-d255-4f6c-9c66-0c727575e338.png)
(in the bash shell type `python3`, install, and `python3 -m pip install bs4`).

There are no extra steps that I need to perform. If you can show a screenshot of your problem, I can help you more precisely.
For now, I can only guess that you do not need to use `sh` to run `iwara-dl.sh`, instead open a git-bash shell and execute `./iwara-dl.sh` so you use `bash` to execute.

Although there are errors, the content of the file can be downloaded. 

About the playlist thing, I've no idea. You can report to the iwara team, and maybe they will fix the issue.

Please let me know if you have more question

**Comment by Lighting-Angel** [comment]
Okay... I tried the same command as yours, after following all the above steps. But now I receive another error

Skip: title missing at page zm21giyy9rsleagma.
Download failed on these videoid:
zm21giyy9rsleagma
Try resuming...
Skip: title missing at page zm21giyy9rsleagma.

I tried on multiple video urls and they all throw the same error

**Comment by hare1039** [comment]
@Lighting-Angel That error is shown when iwara-dl cannot access the webpage. For example, the id from your comment `zm21giyy9rsleagma` i.e. `https://ecchi.iwara.tv/videos/zm21giyy9rsleagma` that I cannot access through my browser. 
So, I recommend that you copy and paste the video you want to download to iwara-dl.
Please try this command `./iwara-dl.sh https://ecchi.iwara.tv/videos/ebdokcox8hv98eek`

Or, if you found a page that iwara-dl cannot download, please let me know which page so I can fix the code.

**Comment by Lighting-Angel** [comment]
I still get the error for every url :(
![Screenshot (10137)_proc](https://user-images.githubusercontent.com/117034298/204343488-45355ecf-3c6e-4316-a41d-e5597d5ca042.jpg)

**Comment by hare1039** [comment]
@Lighting-Angel Then please check that `curl https://ecchi.iwara.tv/videos/ebdokcox8hv98eek` outputs a webpage (HTML document).
For example, this webpage is 44248 bytes. 
If the same error still occurs, please edit the shell script (`iwara-dl.sh`) in the first line and add `set -x;` and send the output log here

**Comment by Lighting-Angel** [comment]
Executing [curl https://ecchi.iwara.tv/videos/ebdokcox8hv98eek] returns the following:

![Screenshot (10139)_proc](https://user-images.githubusercontent.com/117034298/204608002-984f0cf1-571d-46d1-a956-3090a0a16fc1.jpg)

But it works when adding -k before the url...

![Screenshot (10140)_proc](https://user-images.githubusercontent.com/117034298/204611176-a4efc934-e65a-403a-b42d-0ba340919e21.jpg)

I removed the # before set -x; in the iwara-dl.sh file and it still shows the same output

![Screenshot (10139)_proc](https://user-images.githubusercontent.com/117034298/204611372-76d437d6-9b76-425a-8dd5-ddbd1ebe9b05.jpg)

**Comment by hare1039** [comment]
@Lighting-Angel Great now we see the reason. So in your system, curl cannot verify the HTTP certificate of `iwara.tv`. 

You can edit the code by skipping verification by adding the `-k` to https://github.com/hare1039/iwara-dl/blob/master/iwaralib.sh#L192 in the `iwaralib.sh`
or please install the proper certificate library.

**Comment by Lighting-Angel** [comment]
I tried adding -k in that line and it now shows this
![Screenshot (10141)_proc](https://user-images.githubusercontent.com/117034298/204617912-c1e396e8-8e3a-4533-94df-508b912f089d.jpg)

Also if you don't mind, can you tell me how to install the proper certificate library? I thought that certificates not being verified is a server problem? Or is the program verifying the certificates bugged?

**Comment by hare1039** [comment]
@Lighting-Angel I add a flag to accept insecure connections on curl.
Please update the repo and use this tool like `./iwara-dl.sh --accept-insecure https://ecchi.iwara.tv/videos/ebdokcox8hv98eek`

I've no idea how to install the certificate on your system. The certificate on Iwara is Let's Encrypt, and your system may not like that. You maybe need to update your system. I think that is an overkill for this tool, so just use the `--accept-insecure` flag.

**Comment by Lighting-Angel** [comment]
Thanks for ur help :)
