### ISSUE TITLE
Download different users' videos to different dirs

### ISSUE THREAD

**Issue by amamiya-yuuko-1225** [hare1039/iwara-dl#16]
Hi,
When I download several different users' videos in a single command like this:
`./iwara-dl.sh --user aaa bbb ccc ddd`
the downloaded videos are not grouped by dirs.
Is there a way to tackle with the problem? If not, since I've written a script to group them using the terminal output info, I may try to integrate it into the project in the future.
Best regards

**Comment by hare1039** [comment]
@amamiya-yuuko-1225 
hey, I implement this function as `iwara-dl --user --cduser-dir 000mmd`
please update to the master branch and give it a try.

Feel free to reopen this if you are not satisfied.

**Comment by amamiya-yuuko-1225** [comment]
Hi, @hare1039 
The new feature works well for me. 
Thanks for the update! 
Best regards
