### ISSUE TITLE
Question about the 'retry' argument

### ISSUE THREAD

**Issue by amamiya-yuuko-1225** [hare1039/iwara-dl#17]
Hi,
Due to the usage part in readme, there is a **retry** argument like this:
`--retry [count]  Max time to retry the download fail`
However, the **count** parameter is not accepted, since the code in **iwara-dl.sh** reads like:
` --retry )
export IWARA_RETRY="TRUE";
shift; ;;
`
and in func **iwara-dl-retry-dl()** in **iwaralib.sh**:
`if [[ "$IWARA_RETRY" != "FALSE" ]] ; then`
It seems that the [count] parameter is not supported yet, so maybe it's better to modify the help info about [retry].
Best regards

**Comment by hare1039** [comment]
@amamiya-yuuko-1225 Thanks
The arguments are not consistent because of the new iwara website and I don't have much time to work on this.

The code is pretty messy now. Feel free to send a PR to make it better
