### ISSUE TITLE
Curious about if it is legal to crawl videos on Iwara in the US

### ISSUE THREAD

**Issue by huangruihaocst** [hare1039/iwara-dl#2]
I am also considering writing one myself and adding more handy features. I saw you are living in the US and wrote this crawler. Anyone has reached out to you and alarmed you? Or any form of bad things ever happened to you?

Thank you so much for your kind help!

**Comment by a1exwang** [comment]
+1

**Comment by hare1039** [comment]
Hi @huangruihaocst,
As far as I know, nobody contacted me on this project. 
I am also in the Iwara's Discord server, and the admins didn't contact me anything about this.
So, I guess it should be safe if you don't abuse the Iwara server.

**Comment by huangruihaocst** [comment]
Thank you for your reply! Your information is very helpful.

By the way, would you mind sharing an estimated number of videos you crawled (something like a 10 or several hundred or something)? It can be a reference for me when writing my own crawler. It's ok if you aren't willing to tell.

**Comment by hare1039** [comment]
@huangruihaocst I have 5703 video files (around 1TB) in my drive. I also deleted around another 1.8 TB videos that I am not interested in. So, in total, I estimate that I had downloaded 15000 videos  last year.
BTW, I had stopped crawling large number of videos now, only downloading from my favorite creators.

**Comment by huangruihaocst** [comment]
Thank you @hare1039! This is very helpful.
