### ISSUE TITLE
What is the license for this software?

### ISSUE THREAD

**Issue by momoandbanana22** [hare1039/iwara-dl#4]
I want to add a feature to this wonderful software. But I am not sure about the license of this software. So, I don't know if it is OK to add features.

**Comment by hare1039** [comment]
Hi @momoandbanana22
I add the MIT license. 
Basically, you can do anything you like with the software. If you like to, you can also send a PR after you add the features.

**Comment by momoandbanana22** [comment]
thank you for your action that add license.
